name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Repo checkout
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup Node.js (Latest LTS - v20)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install dependencies
      - name: Install dependencies
        run: npm install

      # 4. Run tests (if available)
      - name: Run tests
        run: npm test
        continue-on-error: true   # agar test fail ho jaye to build phir bhi chale

      # 5. Build project
      - name: Build web assets
        run: npm run build

      # 6. Upload build output
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            dist
            build
